// <auto-generated />
namespace mosh_practice.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addMovieProperty_and_GenreTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addMovieProperty_and_GenreTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202106191321576_addMovieProperty_and_GenreTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
